name: Build and Update Images Backend

on:
  push:
    paths:
      - 'backend/**'

jobs:
  build_backend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Extract Git Commit ID
      run: |
        echo "GIT_COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV
        echo "GIT_COMMIT_SHORT=$(echo $GIT_COMMIT | cut -c 1-7)" >> $GITHUB_ENV

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Docker Build and Push for Backend
      run: |
        docker build -t your_dockerhub_username/backend:${{ github.run_number }}-${{ env.GIT_COMMIT_SHORT }} backend/
        docker push your_dockerhub_username/backend:${{ github.run_number }}-${{ env.GIT_COMMIT_SHORT }}
