name: Build and Update Images Backend

on:
  push:
    paths:
      - 'backend/**'

jobs:
  build_backend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Extract Git Commit ID
      run: |
        GIT_COMMIT=$(git rev-parse HEAD)
        GIT_COMMIT_SHORT=$(echo $GIT_COMMIT | awk '{print substr($0,1,7)}')
        echo "GIT_COMMIT_SHORT=$GIT_COMMIT_SHORT" >> $GITHUB_ENV

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Docker Build and Push for Backend
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ github.run_number }}-${{ env.GIT_COMMIT_SHORT }} backend/
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ github.run_number }}-${{ env.GIT_COMMIT_SHORT }}

    - name: Save GIT_COMMIT_SHORT to a file
      run: echo "${{ env.GIT_COMMIT_SHORT }}" > git_commit_short.txt

    - name: Upload GIT_COMMIT_SHORT as artifact
      uses: actions/upload-artifact@v2
      with:
        name: git_commit_short
        path: git_commit_short.txt


  deploy:
    needs: [build_backend]
    runs-on: ubuntu-latest
    steps:
    - name: Download GIT_COMMIT_SHORT artifact
      uses: actions/download-artifact@v2
      with:
        name: git_commit_short
        path: git_commit_short.txt

    - name: Set GIT_COMMIT_SHORT env from artifact
      run: |
        ls git_commit_short.txt
        echo "GIT_COMMIT_SHORT=$(cat git_commit_short.txt)" >> $GITHUB_ENV


    - name: Checkout ArgoCD repository
      uses: actions/checkout@v2
      with:
        repository: "nicolasjulian/argocd-howtofixcvedotcom"

    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v2.0.0
      with:
        kustomize-version: "5.1.1"

    - name: Update Kubernetes resources
      run: |
       cd Application/production
       kustomize edit set image ${{ secrets.DOCKERHUB_USERNAME }}/backend=${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ github.run_number }}-${{ env.GIT_COMMIT_SHORT }}
       cat kustomization.yaml

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.DEPLOY_KEYS }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Bump docker tag"

    - name: Push to Repos
      run: |
        git remote set-url origin git@github.com:nicolasjulian/argocd-howtofixcvedotcom.git
        GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=~/.ssh/known_hosts" git push origin main
