name: Build and Update Images Frontend

on:
  push:
    paths:
      - 'frontend/**'

jobs:
  build_frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Extract Git Commit ID
      run: |
        echo "GIT_COMMIT=$(git rev-parse HEAD)"
        echo "GIT_COMMIT_SHORT=$(echo $GIT_COMMIT | cut -c 1-7)"
        echo "GIT_COMMIT_SHORT=$GIT_COMMIT_SHORT" >> $GITHUB_ENV

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Docker Build and Push for Frontend
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ github.run_number }}-${{ env.GIT_COMMIT_SHORT }} frontend/
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ github.run_number }}-${{ env.GIT_COMMIT_SHORT }}
